### PR TITLE
Install nnvm lib and haders. Offer choice to build static or shared lib.

### PR DESCRIPTION
**Pull request by weijianwen**
Following advice in #140, add options for static/shared building and install targets and headers into destination. Via spack package management, MXNet version 0.10.0.post2 built against the this nnvm static lib passes the `tests/python/unittest` and `tests/python/train` tests.

```
$ spack install py-mxnet+cuda %gcc@4.8.5 ^mxnet+profiler ^python@2.7.13
```

### CODE REVIEW

**Comment by weijianwen** [comment]
Could you explain more details about library name? I intend to build NNVM as a third-party static library outside MXNet's source tree. After that, MXNet is built via its `Makefile` in which NNVM's libname is hardcoded as `libnnvm.a`. That's exactly the library name NNVM has.

I haven't tried building MXNet itself via CMake. This commit doesn't change NNVM's default choice of building a shared lib, thus it shouldn't affect MXNet's CMake usage.

**Comment by cjolivier01** [comment]
Ok

**Comment by cjolivier01** [comment]
Ok

**Comment by tqchen** [comment]
I am going to merge this for now. However, note that the current build script do not package the recent nnvm compiler distro

**Comment by weijianwen** [comment]
Thank you @tqchen . This PR is part of work in progress in Spack https://github.com/LLNL/spack/pull/3579 , hoping to simplify build of MXNet on various distros with customized flags (cpu?gpu?openmp?) and auto dependency resolution (zeromq, openbla, cudnn...). Last stable version 0.10 has been built successfully. I plan to try 0.11 and more feedbacks are coming.

**Pull request merged**
