### PR TITLE
Flatten node injection before softmax as softmax expects the input in…

### PR DESCRIPTION
**Pull request by srkreddy1238**
… 2D (#336)

### CODE REVIEW

**Comment by tqchen** [comment]
cc @zhreshold can you review this?

**Comment by zhreshold** [comment]
`axis` is supported by softmax, therefore no need to flatten it.

**Comment by masahi** [comment]
@srkreddy1238 I have a PR at dmlc/tvm#882 which includes support for arbitrary dimension softmax.

**Comment by srkreddy1238** [comment]
Thanks for the axis support. It works good with graph compilation.

**Pull request closed without merging**
