### PR TITLE
Expose clip to frontend mxnet

### PR DESCRIPTION
**Pull request by ehsanmok**
[#511](https://github.com/dmlc/nnvm/issues/511)

### CODE REVIEW

**Comment by ehsanmok** [comment]
@tqchen you'd need to update mxnet to v1.2 where MobilenetV2 was added [recently](https://github.com/apache/incubator-mxnet/pull/10879).

**Comment by tqchen** [comment]
CI update is a bit brittle and we would consider doing it later, can you remove the mobilenet mxnet test for now? Just adding unittest of clip will do

**Comment by ehsanmok** [comment]
@tqchen sure, but shall I keep the added `get_gluon_output` in test? as you know, pretrained models are all now in gluon.

**Comment by tqchen** [comment]
sounds good

**Comment by ehsanmok** [comment]
@tqchen ping

**Comment by tqchen** [comment]
Thanks, this is merged

**Pull request merged**
