### PR TITLE
Change the way to import ONNX model. (cf. #186)

### PR DESCRIPTION
**Pull request by imai-lm**
As I wrote in #186 , This seems a better way to import ONNX model.

### CODE REVIEW

**Comment by imai-lm** [comment]
In the Jenkins testing environment, apparently `onnx.load()` returns a GraphProto object, while in my environment it returns a ModelProto object...

**Comment by imai-lm** [comment]
I will withdraw this PR, because it is from my master branch. I did it due to my slacking off, but apparently it's no good for future potential contributions. I'll do the same PR again later.

**Comment by PENGUINLIONG** [comment]
You didn't do anything wrong. The __latest__ docs said that `onnx.load()` returns a `ModelProto` according to [this](https://github.com/onnx/onnx/blob/07a9c2b7ea246345446761329558b1edfb86b96a/onnx/__init__.py#L20).

However, it was about 23 days before, __they redefined the function `load()`__. [Before that](https://github.com/onnx/onnx/commit/07a9c2b7ea246345446761329558b1edfb86b96a#diff-af5375b7114884527be026ea3b855569), we seriously have a `GraphProto` returned. How devastating.

**Comment by imai-lm** [comment]
What a disaster. [The release note of v0.2](https://github.com/onnx/onnx/releases/tag/v0.2) also tells:
> Introduction of `ModelProto` to represent top-level model in addition to `GraphProto`

**Pull request closed without merging**
