### PR TITLE
[JSON] attr->attrs in node attribute, keep backward read compatible

### PR DESCRIPTION
**Pull request by tqchen**

### CODE REVIEW

**Comment by tqchen** [comment]
@piiswrong

**Comment by piiswrong** [comment]
why?

**Comment by tqchen** [comment]
To be consistent with the graph attributes(which is named as attrs) and other naming(e.g. inputs instead of input)

**Comment by tqchen** [comment]
@piiswrong followup on this?

**Comment by piiswrong** [comment]
what graph attributes?

**Comment by tqchen** [comment]
When we save graph, the graph attributes(shape type) are stored as attrs instead of attr

**Pull request merged**
