### PR TITLE
Issue fix for tiny yolo

### PR DESCRIPTION
**Pull request by PariksheetPinjari909**
There was an issue in maxpool frontend for tiny-yolo. It is fixed in this PR. 
https://github.com/dmlc/nnvm/issues/431

### CODE REVIEW

**Comment by kaishijeng** [comment]
@PariksheetPinjari909 

Are yolo2 and yolo3 supported?
I got segmentation fault.
 From darknet website, it has yolo1, yolo2, and yolo3. Also yolo1-tiny, yolo2-tiny and yolo3-tiny.

Thanks,

**Comment by PariksheetPinjari909** [comment]
Currently yolo2 and yolo2-tiny are supported. I am working on yolov3, and i will PR this soon

**Comment by kaishijeng** [comment]
I found out there is no yolo2 and yolo2-tiny.
It should yolov2 and yolov2-tiny.

However,
yolov2: OK
yolov2-tiny: segmentation fault

Thanks,

**Comment by kaishijeng** [comment]
@PariksheetPinjari909 

What is difference of cfg files from https://github.com/siju-samuel/darknet and https://github.com/pjreddie/darknet?

Thanks,

**Pull request merged**
