### PR TITLE
[WIP] Infer Storage Type pass for sparse tensors

### PR DESCRIPTION
**Pull request by eric-haibin-lin**
Please don't merge this in.

### CODE REVIEW

**Comment by piiswrong** [comment]
@tqchen  Would storage type be a better name?

**Comment by eric-haibin-lin** [comment]
I prefer using storage type to chunk type.

**Comment by tqchen** [comment]
storage type sounds good

**Comment by eric-haibin-lin** [comment]
TODO: disable mem sharing locally instead of globally. 
Merge in a separate sparse branch for now.

**Comment by eric-haibin-lin** [comment]
@piiswrong Added kDynamicStorage 

ping @reminisce for awareness

**Pull request merged**
