### PR TITLE
Initial NHWC layout support

### PR DESCRIPTION
**Pull request by masahi**
Support NHWC layout for conv, pooling, upsampling, and softmax.
A simple test case is included. 

@srkreddy1238

### CODE REVIEW

**Comment by tqchen** [comment]
nice work, can you add a testcase for NHWC case you added?

**Comment by masahi** [comment]
what do you mean? A test case is already included at tests/python/compiler/test_nhwc_layout.py.

**Comment by tqchen** [comment]
ah, sorry that i missed the code when i glance over, this can now be merged.

**Comment by srkreddy1238** [comment]
I have a full model on NHWC with conv, pool & softmax.

I will test today and conclude the functionality :)

Siva

**Pull request merged**
