### PR TITLE
change to match by both op and name

### PR DESCRIPTION
**Pull request by piiswrong**

### CODE REVIEW

**Comment by tqchen** [comment]
Why do we need match by name?

**Comment by piiswrong** [comment]
it's safer. Some times you can use the same op for different ingrad

**Comment by tqchen** [comment]
I assume it is not safer, since there is no requirements in the naming spec. Supporting this will enable ops that relies on this feature(which is not very reliable) we should not do this unless there is a concrete op that does so

**Comment by piiswrong** [comment]
reverted.
please have a look at the rest

**Pull request merged**
